name: 'CI/CD'
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'master'
concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true
defaults:
  run:
    shell: bash
jobs:
  # Build and test
  Build-and-Test:
    runs-on: ubuntu-latest
    container: ghcr.io/galacticusorg/buildenv:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
      - name: Generate configure
        run: |
          cd $GITHUB_WORKSPACE
          apt update
          apt install -y bison flex valgrind
          git config --global --add safe.directory $GITHUB_WORKSPACE
          set -o pipefail
          mkdir -p config
          mkdir -p m4
          touch config/config.rpath
          autoreconf --install --force -I/usr/local/share/aclocal
          CFLAGS="-I/usr/include/x86_64-linux-gnu -g" ./configure
          make dist
          cd doc
          make libmatheval.html
      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: release-archive
          path: 'libmatheval-1.1.12.tar.gz'
      - name: Upload docs artifact
        uses: actions/upload-artifact@v6
        with:
          name: docs
          path: 'doc/libmatheval.html'
      - name: Test code
        run: |
          gcc t.c -I/usr/local/include -L/usr/local/lib -lmatheval -g
          valgrind --track-origins=yes ./a.out
      - name: Build and test
        run: |          
          make -j4 2>&1 | tee build.log
          grep -v -q Error: build.log
          grep -v -q Warning: build.log
          (make -j4 check || { cat tests/testsuite.log; exit 1; }) 2>&1 | tee build.log
          grep -v -q Error: build.log
          grep -v -q Warning: build.log
          set +o pipefail
